spring:
  application:
    name: CochaVive
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_LINK}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}

  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration-time: ${JWT_EXPIRATION_TIME}

    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}

logging:
  level:
    cocha:
      vive:
        backend: ${APP_LOG_LEVEL:INFO}

unleash:
  app-name: cocha-vive-unleash
  instance-id: unleash-onboarding-instance
  api-url: https://primary-production-0ced61.up.railway.app/api/
  api-token: ${UNLEASH_API_TOKEN}
  environment: production
  fetch-toggles-interval: 15
